export const RECEIVE_TASKS_REQUEST = 'RECEIVE_TASKS_REQUEST';
export const RECEIVE_TASKS_SUCCESS = 'RECEIVE_TASKS_SUCCESS';

export const SEND_TASK_REQUEST = 'SEND_TASK_REQUEST';
export const SEND_TASK_SUCCESS = 'SEND_TASK_SUCCESS';

export const DELETE_TASK_REQUEST = 'DELETE_TASK_REQUEST';
